sencrop/github-workflows

.github/workflows/terraform-plan-ecs-v1.yml, .github/workflows/terraform-plan-v1.yml, README.md
Create a common Github workflow to display terraform plan in Github. This should help be helpful in different ways:
- Reviewers of a terraform change would easily read the plan
- Running local terraform plan can be tedious (you need to get the creds and the command line parameter right) or too heavy to run locally.
- Changes to [terraform-modules](https://github.com/sencrop/terraform-modules) are propagated silently to applications, this will make them visible.
Implementation choices:
- The plan is performed against the `preproduction` and `production` environment using the current image tag. This way we avoid displaying a plan that has upcoming changes in each PR but only when there is substantial infrastructure changes.
- The Github message is as light as possible to make changes as …
=> Add terraform plan workflow

.github/workflows/ecs-deploy-v1.yml, README.md
This new workflow is a factorisation of the standard deployment of our ecs applications through terraform.
This PR also adds two new feature to that workflow:
- The workflow will wait until the deployment has been completed 
- The workflow will notify the outcome of the deployment to a slack channel
=> Add a new workflow to deploy ecs applications

.github/workflows/docker-push-v2.yml
The current action from satackey is stale. Switching to a maintained repo + split the cache per image name.
=> chore(docker): update docker caching action

.github/workflows/ecs-deploy-v2.yml, .github/workflows/terraform-apply-v2.yml, .github/workflows/terraform-plan-ecs-v2.yml, .github/workflows/terraform-plan-v2.yml
this will remove the need to define the terraform version in each Github actions workflow which will make the upgrade of terraform easier
=> feat: add dynamic lookup of terraform version

.github/workflows/version-v2.yml, README.md
This workflow provides a standard version of the version computing so we can replace this:
```
version:
runs-on: ubuntu-latest
outputs:
docker_image_tag: ${{ steps.compute_ref.outputs.REF }}
steps:
- name: checkout
uses: actions/checkout@v3
- name: Get commit hash
id: compute_ref
run: |
REF=${GITHUB_REF#refs/tags/}
echo "REF=$REF" >> ${GITHUB_OUTPUT}
```
by this
```
version:
uses: sencrop/github-workflows/.github/workflows/version-v2.yml@master
```
=> feat: add a workflow to standardize version compute

.github/workflows/ecs-deploy-v2.yml, README.md, actions/notify-deployment-in-progress/action.yaml, actions/track-deployment-time/action.yaml
This PR adds 2 custom actions to track deployments:
- `notify-deployment-in-progress` this action encapsulate the logic of notifying when a deployment is in progress on slack that already exists (this logic in currently duplicated in several non standard repos such as `infrastructure-sencrop`). In this PR we also add an event to Datadog so we can easily graph and correlate deployment events.
- `track-deployment-action`: this action reports to Datadog as a metric the deployment time of a service
=> feat: add deployment tracking action

actions/track-deployment-time/action.yaml
retried pipeline are often faster because we only retry a subpart of the actions so it's useful to be able to filter them out from dashboards
=> feat: add a retry tag on deployment time metric

.github/workflows/docker-push-v2.yml
cf docker action doc: https://github.com/docker/build-push-action?tab=readme-ov-file#inputs
And docker doc for the values: https://docs.docker.com/engine/reference/commandline/buildx_build/#platform
Passing `local` as a default should match the behaviour where no flag is passed if I understood well
=> add platforms option to docker push action

.github/workflows/docker-push-v2.yml
Based on errors in https://github.com/sencrop/sencrop-bali-api/actions/runs/7714240306/job/21026033336
I guess we need to setup QEMU as shown in the docs of the docker push action: https://github.com/docker/build-push-action?tab=readme-ov-file
=> Add qemu setup to docker push action

.github/actionlint-matcher.json, .github/workflows/lint.yml, .github/workflows/terraform-plan-ecs-v2.yml, .github/workflows/terraform-plan-v2.yml
PR to fixes the linter results:
- https://github.com/sencrop/github-workflows/pull/78
- https://github.com/sencrop/github-workflows/pull/80
=> [SENP-531] feat(ci): add actionlint check

.github/workflows/ecs-deploy-v2.yml, README.md, actions/lookup-git-hash/action.yaml, actions/lookup-git-tag/action.yaml, actions/notify-deployment-in-progress/action.yaml
**ecs-deploy**:
- `docker_image_tag` is now optional on the `ecs-deploy` deploy workflow, this will make applications that have a static image tag easier to configure.
- `docker_image_tag` is now deprecated in favour of `version`, this term is closer to the level of abstraction of this workflow.
- when using `version` one might set `use_version_as_docker_image_tag` to `false` to avoid the version being passed as docker_image_tag to the terraform apply (default is `true`, this is the most common usage)
**deployment-notification**:
- `current_version` is now deprecated in favour of `former_version` and `deployed_version` in favour of `new_version`, this should reduce the ambiguity when using this action.
=> [SENP-648] feat(ecs-deploy): improve consistency of workflows parameters

.github/workflows/netlify-deploy-preview-v1.yml
As it is unnecessary / redundant regarding the usage of custom subdomains with application name: 
- https://app-preview-staging-4963.app.preview.sencrop.com > https://staging-4963.app.preview.sencrop.com
- https://back-office-preview-staging-438.backoffice.preview.sencrop.com > https://staging-438.backoffice.preview.sencrop.com
=> feat(preview): remove application name from netlify preview alias

.github/workflows/netlify-deploy-preview-v1.yml, .github/workflows/netlify-deploy-v1.yml
Since the application is deployed in two netlify sites (staging and production), we need to provide the right site_id while requesting a deployment to prevent any inconsistencies instead of relying on a single secret definition here
This is an example of why I'd suggest not to rely to much on context parameters such as env variables or secrets from the calling action as we don't really hold what's going on, it is not as explicit as it should be. 
Maybe we should ask for more parameters and get a standalone action which basically does as it says retrieving all the input parameters 🤔
=> feat(netlify): add netlify site_id as parameter

.github/workflows/release-please-v1.yml
This workflow perform authentication using the `sencrop-release-bot` credentials before running release-please (avoid the needs of a user PAT token).
=> feat: add release-please workflow

.github/workflows/terraform-deploy-v1.yml
This workflow has a higher abstraction level than terraform apply. It should be used to deploy application that are managed by terraform but are not ECS applications.
=> feat: add terraform-deploy workflows

.github/workflows/ecs-deploy-v2.yml
Some application such as `intake-stats` don't use yet a `v*` version.
As application that requires this validation have been migrated to ecs-deploy-v3 we can remove this check from the v2 version while are migrating the rest of the repositories to the standard release.
=> fix(ecs-deploy): remove version format validation from ecs-deploy-v2

.github/workflows/release-please-v1.yml
Some repositories don't have a preproduction environment and release continuously every merge to master.
Using the release-please PR on this repositories would be a step back as release would take one additional step.
With this pull request we introduce the `use_release_pr` flag, when set to false the release will be created directly without going through a pull request.
Note that this was not possible with release-please by itself as it must create a pull request: https://github.com/googleapis/release-please/issues/1696. We use `semantic-release-action` instead which is likely what release-please use under the hood.
=> feat(release-please): add support for continuous release

.github/workflows/docker-experiment-v1.yml, .github/workflows/docker-push-v3.yml, .github/workflows/docker-tag-v1.yml, .github/workflows/ecs-deploy-v3.yml, .github/workflows/ecs-restart-v2.yml, .github/workflows/ecs-start-v2.yml, .github/workflows/ecs-stop-v2.yml, .github/workflows/netlify-deploy-preview-v1.yml, .github/workflows/netlify-deploy-v1.yml, .github/workflows/node-module-cache-v1.yml, .github/workflows/rds-start-v2.yml, .github/workflows/rds-stop-v2.yml, .github/workflows/release-please-v1.yml, .github/workflows/terraform-apply-v2.yml, .github/workflows/terraform-deploy-v1.yml, .github/workflows/terraform-plan-ecs-v3.yml, .github/workflows/terraform-plan-v2.yml, .github/workflows/version-v3.yml
This change will make the swap to ARM easier.
At some point we might make `ubuntu-latest-arm` the default runner of most workflows
=> feat: allow to override runs-on

.github/workflows/docker-experiment-v1.yml, .github/workflows/ecs-deploy-v3.yml
Experimental build will have the `x` prefix e.g. `x1234330`. Having a dedicated prefix allow to apply different rules for experimental build, such as deploy to prod in this pull request.
=> fix(experimental): add a prefix to experimental build version

.github/actionlint.yaml, .github/workflows/docker-experiment-v2.yml, .github/workflows/docker-push-v4.yml
This PR is an attempt to remove the ambiguity around cpu architecture for image build:
- `cpu_architecture` parameter is added and made mandatory: a default architecture for image build doesn't make sense as it is not obvious for the user which architecture is the default one. This will also make the update of workflows easier when switching the architecture.
- `runs_on` parameter is removed: this limit the type of runner that can be use for docker build but we currently don't have any use case of docker build being performed on other runners than `ubuntu-latest` or `ubuntu-latest-arm64` and this won't change in the foreseeable future.
- `target_platforms` is removed: this parameter allowed us to perform cross platform build using QEMU, this was never really used because this approach is …
=> chore(docker): explicit interface for cpu architecture

.github/workflows/ecs-deploy-v3.yml, .github/workflows/terraform-deploy-v1.yml
Follow up of slack issue https://sencrop.slack.com/archives/C046SM8RVFD/p1728372180545099
We need to prevent moving the "environment" tag to the branch being ran with experiment flow as it won't be reachable from the base branch later on.
=> chore: add env tag for base branch only

.github/workflows/node-module-cache-v1.yml, actions/npm-ci-with-cache/action.yaml
This PR adds the cpu architecture to the cache key. Some libraries (e.g. `esbuild`) are compiled for the target cpu architecture so we can't share the same cache between runners with different architecture.
=> chore(node-modules-cache): add architecture to cache key

.github/workflows/node-module-cache-v1.yml
Reverts sencrop/github-workflows#169
=> Revert "chore: use arm64 as default for node-module-cache"

.github/workflows/docker-tag-v1.yml
Third try to make this change, github workflows actually sets `shell: bash -e {0}` by default cf [doc](https://github.com/sencrop/github-workflows/pull/176) which makes an intermediate command failure fail the entire script.
Setting `shell: bash {0}` to override the default should finally fix the issue.
=> chore(docker-tag): do not fail if tag already exists - v3

.github/workflows/node-module-cache-v1.yml
This workflow is architecture dependant so this parameter should not be optional.
=> feat(node-module-cache): remove runs_on in favor of cpu_architecture

.github/workflows/docker-push-v4.yml
Currently images are generated with an image index set to `application/vnd.oci.image.index.v1+json` which is unsupported for some use-cases like containers for lambdas.
It is mostly used for multi-arch builds purposes which we are not doing at the moment.
Setting the provenance to false seems to be the best workaround for us based on the comments found here: https://github.com/docker/buildx/issues/1509#issuecomment-1378538197
=> fix(docker-build-push): disable provenance attestation

.github/workflows/ecs-deploy-v3.yml, .github/workflows/terraform-deploy-v1.yml
Since https://github.com/sencrop/github-workflows/pull/165 the `production` tag is not moving anymore, that's because a production release workflow is triggered from a tag and not from a branch
=> fix: production tag is not moving

.github/workflows/node-module-cache-v2.yml
Related to this [thread](https://sencrop.slack.com/archives/C046SM8RVFD/p1739288858854679), this PR evolves the `node-module-cache` to v3 bringing the support of multiple CPU architecture.
Do we have a depreciation process and a test process @jdassonvil?
Edit: I tested it [here](https://github.com/sencrop/sencrop-bali-api/actions/runs/13282117605) and the bali database migration is [fixed](https://github.com/sencrop/sencrop-bali-api/actions/runs/13282324825/job/37083342507), LGTM.
=> feat(workflow/node-module-cache): support multiple cpu arch

.github/workflows/release-please-v1.yml
Following the release please official documentation https://github.com/googleapis/release-please-action?tab=readme-ov-file#supporting-multiple-release-branches
This operation should be not breaking on every repos if they have only 
```
on:
push:
branches:
- master
```
And this should help when having this configuration:
```
on:
push:
branches:
- master
- "v[0-9]+"
```
=> feat: add target-branch parameter

.github/workflows/release-please-v1.yml
This PR adds permissions for the `release-please` to create a new label, see https://github.com/googleapis/release-please-action/issues/1105.
=> ci(release-please): add permissions to write issues
